services:
  app:
    build: .
    container_name: docservice_app
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./data:/docserver/data
    environment:
      DATABASE_URL: sqlite:///./data/app.db
    restart: unless-stopped